### ISSUE TITLE
Pickup screen bug while make an order from local ekrut machine

### ISSUE THREAD

**Issue by Talgaon4** [almogkh/Ekrut-Project#73]
Run ekrut-client with "Afula" as argument.
Cick on Create Order nutton.
Create an order.
Click on View Cart.
Click on Cancle Order button, and approve.
Now the sceen is loaded is unknown screen, and also you can choose shipment from there etc..
* The pickup button is not available at the moment.
![a411f5ee-af6a-4534-8650-74ffb24940fd](https://user-images.githubusercontent.com/96999217/211627379-ad6353f9-0f85-4d14-a2d3-732596e10b22.jpg)

**Comment by Talgaon4** [comment]
Another small issue, when you finish an order without selecting items at all, the system still allows you to make an order including payment and order confirmation.

**Comment by almogkh** [comment]
Fixed by 5c6600c1c892586c45e476daae83b3eb11c914ba and c3401c67a7f2a7546a68df665847523b582387a2
